### ISSUE TITLE
Migrate to extJWNL 1.8.0

### ISSUE THREAD

**Issue by psych0naut** [dkpro/lsr#2]
DKPro LSR depends on JWNL, a long-unmaintained Java library for WordNet.  Modern NLP code is increasingly moving to extJWNL, a fork of JWNL which is well maintained.  Unfortunately, recent versions of extJWNL clash with JWNL; it's not possible to have both dependencies in the same project, so much recent NLP code which depends on extJWNL cannot use DKPro LSR any more.  (See https://github.com/extjwnl/extjwnl/issues/1 for further details.)

I suggest migrating DKPro LSR from JWNL to extJWNL.  This should be pretty painless; the API is mostly the same, and the WordNet properties file syntax is only slightly different.

**Comment by zesch** [comment]
After some thoughts, it would probably be better to directly migrate to Uby wrappers.
Feel free to re-open if you think that this does not solve the problem

**Comment by reckart** [comment]
You mean LSR should move to Uby or the code that uses LSR should move to Uby and LSR stays as it is?

**Comment by zesch** [comment]
The proposal is to add LSR wrappers based on Uby instead of the native APIs
within LSR.
This could at some point move to Uby if we don't want to keep the LSR
project.

2015-04-07 22:36 GMT+02:00 Richard Eckart de Castilho <
notifications@github.com>:

**Comment by chmeyer** [comment]
Do we have projects other than dkpro-similarity that use/depend on LSR?

**Comment by psych0naut** [comment]
DKPro WSD uses DKPro LSR.  Or rather, it has a module which optionally allows users to create a DKPro LSR–backed sense inventory.  I'm not aware of anyone who is actively using this module; possibly it wouldn't be missed if it were removed.

**Comment by zesch** [comment]
dkpro toolbox also uses LSR.

2015-04-07 22:46 GMT+02:00 Christian M. Meyer <notifications@github.com>:

**Comment by logological** [comment]
Duplicate of Issue #4.
